version: "3.9"

services:
  app:
    build: .
    container_name: authorization
    restart: always
    ports:
      - "3000:3000"

#   mongo:
#     image: mongo:6
#     container_name: my_mongo
#     restart: always
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo_data:/data/db

# volumes:
#   mongo_data:
